In [1]:
import pandas as pd
import ollama

In [2]:
# Initialize the Ollama client, specifying the host and port
# This assumes Ollama is running on localhost:11434
ollama.api_base = 'http://localhost:11434'

# Example usage:
# response = ollama.chat(model='qwen2.5:14b', messages=[
#   {'role': 'user', 'content': 'Why is the sky blue?'},
# ])
# print(response['message']['content'])

In [4]:
df = pd.read_csv("http://192.168.1.158:9001/api/v1/download-shared-object/aHR0cDovLzEyNy4wLjAuMTo5MDAwL2hvbWUvc2lsdmVyL1RBVC1RQS9wcmVwYXJlZF90cmFpbl9kYXRhLmNzdj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPVIzTVVPWjJPQlVCSU1VQlpCV1hGJTJGMjAyNTEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjA2VDA4NDUzNlomWC1BbXotRXhwaXJlcz00MzIwMCZYLUFtei1TZWN1cml0eS1Ub2tlbj1leUpoYkdjaU9pSklVelV4TWlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKaFkyTmxjM05MWlhraU9pSlNNMDFWVDFveVQwSlZRa2xOVlVKYVFsZFlSaUlzSW1WNGNDSTZNVGMyTlRBMU16RXhOeXdpY0dGeVpXNTBJam9pWVdSdGFXNGlmUS41aHlYWnhCbEFXRHY1Y0lROFdoT0ZIeF91NXg3aVJsSHFtRktkVHpDNHFuOHRBanJDTGJKbWYzeENWX0JIbTVVUUs4cm1ScExaUWU2Rkd5NFJFTWR3QSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmdmVyc2lvbklkPW51bGwmWC1BbXotU2lnbmF0dXJlPThmMmM1ZTk0N2M0MmNkMmM1ZjFhYzNkZDg2YTUzOWM5ZWU5YTVlMzlmZTU2MzkzMjRjNWUyNGMwZDA0M2NjYWI")

In [5]:
df

,Unnamed: 0,answer_type,questions,derivation,mapping,facts,answer,scale,paragraphs,table,operator_label
0,0,multi-span,What does the Weighted average actuarial assum...,NaN,"{'table': [[3, 0], [2, 0], [4, 0]]}","['Discount rate', 'Rate of increase in salarie...","['Rate of inflation', 'Rate of increase in sal...",NaN,Actuarial assumptions The Group’s scheme liabi...,"[['', '2019 %', '2018 %', '2017 %'], ['Weighte...",2.0
1,1,span,How much is the 2019 rate of inflation?,NaN,"{'table': [[2, 1]]}",['2.9'],['2.9'],percent,Actuarial assumptions The Group’s scheme liabi...,"[['', '2019 %', '2018 %', '2017 %'], ['Weighte...",1.0
2,2,span,How much is the 2018 rate of inflation?,NaN,"{'table': [[2, 1]]}",['2.9'],['2.9'],percent,Actuarial assumptions The Group’s scheme liabi...,"[['', '2019 %', '2018 %', '2017 %'], ['Weighte...",1.0
3,3,arithmetic,What is the 2019 average rate of inflation?,(2.9+2.9)/2,"{'table': [[2, 1]]}",['2.9'],2.9,percent,Actuarial assumptions The Group’s scheme liabi...,"[['', '2019 %', '2018 %', '2017 %'], ['Weighte...",4.0
4,4,arithmetic,What is the 2019 average rate of increase in s...,(2.7+2.7)/2,"{'table': [[3, 1]]}",['2.7'],2.7,percent,Actuarial assumptions The Group’s scheme liabi...,"[['', '2019 %', '2018 %', '2017 %'], ['Weighte...",4.0
...,...,...,...,...,...,...,...,...,...,...,...
12825,13208,arithmetic,What was the percentage change in total revenu...,"(36,709-35,705)/35,705","{'table': [[7, 2], [7, 3]]}","['35,705', '36,709']",2.81,percent,Product Revenue by Groups of Similar Products ...,"[['', '', 'Years Ended', '', '2019 vs. 2018', ...",3.0
12826,13209,span,What information is provided in Note 21?,NaN,"{'paragraph': {'2': [[51, 98]]}}",['further information on fair value hierarchie...,['further information on fair value hierarchie...,NaN,NOTE 19 – DERIVATIVE FINANCIAL INSTRUMENTS Ple...,"[['USDm', '2019', '2018'], ['Fair value of der...",0.0
12827,13210,multi-span,What are the types of derivative financial ins...,NaN,"{'table': [[4, 0], [3, 0]]}","['Bunker swaps', 'Forward freight agreements']","['Forward freight agreements', 'Bunker swaps']",NaN,NOTE 19 – DERIVATIVE FINANCIAL INSTRUMENTS Ple...,"[['USDm', '2019', '2018'], ['Fair value of der...",2.0
12828,13211,multi-span,What are the types of derivative financial ins...,NaN,"{'table': [[7, 0], [6, 0]]}","['Forward exchange contracts', 'Interest rate ...","['Forward exchange contracts', 'Interest rate ...",NaN,NOTE 19 – DERIVATIVE FINANCIAL INSTRUMENTS Ple...,"[['USDm', '2019', '2018'], ['Fair value of der...",2.0
12829,13212,span,In which year was the amount of forward exchan...,|1.8|>|0.4|,"{'table': [[0, 2]]}",['2018'],['2018'],NaN,NOTE 19 – DERIVATIVE FINANCIAL INSTRUMENTS Ple...,"[['USDm', '2019', '2018'], ['Fair value of der...",1.0

In [6]:
df.loc[df['questions'] == "What was included therein within the net interest expenses?"]

,Unnamed: 0,answer_type,questions,derivation,mapping,facts,answer,scale,paragraphs,table,operator_label
305,313,span,What was included therein within the net inter...,NaN,"{'table': [], 'paragraph': {'3': [[20, 76]]}}",['Interest effect from the adjustment of the a...,['Interest effect from the adjustment of the a...,NaN,The pension expenses of the direct and indirec...,"[['€ million', '2017/2018', '2018/2019'], ['Cu...",1.0

In [26]:
sys_prompt = """
You are a data generator for training a financial analysis reasoning model.

Your job is to create high-quality synthetic training examples that teach a model to:
- Read small financial tables
- Interpret questions about financial performance
- Explain step by step how to reason through a financial dataset to answer complex mathematical and financial questions
- Wrap the question/prompt in <prompt> ... </prompt> tags
- Wrap the paragraphs and tables under <context> ... </context> tags
- Come up with a detailed user intent behind the prompt based on the prompt itself and the paragraphs and tables.
- Perform accurate calculations (margins, variances, ratios, trends)
- Explain reasoning step-by-step
- The user intent, calculations and reasoning should be wrapped under <thinking> ... </thinking> tags
- Produce a clear final answer beginning with: "Final answer:". Be as detailed as possible in explaining the final answer. The whole part with the final answer should be wrapped in <answer> ... </answer> tags

RULES:
- Chain-of-thought must be logically correct.
- End the example with a single “Final answer:” line.
"""

In [27]:
user_prompt = """
    Here is the user question: {},
    Here are the paragraphs and tables to serve as your context {},
    Here is the actual evidence that you need to consider from the contexts: {},
    Here is the answer type {},
    Here is the derivation of the answer {},
    Here is the final answer (You need to expound on this):  {}
    Here is the scale at which the answer is expressed: {}
"""

In [28]:
df.columns

Index(['Unnamed: 0', 'answer_type', 'questions', 'derivation', 'mapping',
       'facts', 'answer', 'scale', 'paragraphs', 'table', 'operator_label'],
      dtype='object')

In [29]:
prompt = sys_prompt + user_prompt.format(df['questions'][0], df['paragraphs'][0]+"\n"+df['table'][0], df['facts'][0], df['answer_type'][0], df['derivation'][0], df['answer'][0], df['scale'][0])

In [30]:
prompt

'\nYou are a data generator for training a financial analysis reasoning model.\n\nYour job is to create high-quality synthetic training examples that teach a model to:\n- Read small financial tables\n- Interpret questions about financial performance\n- Explain step by step how to reason through a financial dataset to answer complex mathematical and financial questions\n- Wrap the question/prompt in <prompt> ... </prompt> tags\n- Wrap the paragraphs and tables under <context> ... </context> tags\n- Come up with a detailed user intent behind the prompt based on the prompt itself and the paragraphs and tables.\n- Perform accurate calculations (margins, variances, ratios, trends)\n- Explain reasoning step-by-step\n- The user intent, calculations and reasoning should be wrapped under <thinking> ... </thinking> tags\n- Produce a clear final answer beginning with: "Final answer:". Be as detailed as possible in explaining the final answer. The whole part with the final answer should be wrapped in <answer> ... </answer> tags\n\nRULES:\n- Chain-of-thought must be logically correct.\n- End the example with a single “Final answer:” line.\n\n    Here is the user question: What does the Weighted average actuarial assumptions consist of?,\n    Here are the paragraphs and tables to serve as your context Actuarial assumptions The Group’s scheme liabilities are measured using the projected unit credit method using the principal actuarial assumptions set out below: Notes: 1 Figures shown represent a weighted average assumption of the individual schemes. 2 The rate of increases in pensions in payment and deferred revaluation are dependent on the rate of inflation.\n[[\'\', \'2019 %\', \'2018 %\', \'2017 %\'], [\'Weighted average actuarial assumptions used at 31 March1:\', \'\', \'\', \'\'], [\'Rate of inflation2\', \'2.9\', \'2.9\', \'3.0\'], [\'Rate of increase in salaries\', \'2.7\', \'2.7\', \'2.6\'], [\'Discount rate\', \'2.3\', \'2.5\', \'2.6\']],\n    Here is the actual evidence that you need to consider from the contexts: [\'Discount rate\', \'Rate of increase in salaries\', \'Rate of inflation\'],\n    Here is the answer type multi-span,\n    Here is the derivation of the answer nan,\n    Here is the final answer (You need to expound on this):  [\'Rate of inflation\', \'Rate of increase in salaries\', \'Discount rate\']\n    Here is the scale at which the answer is expressed: nan\n'

In [31]:
response = ollama.chat(model='qwen2.5:14b', messages=[
  {'role': 'user', 'content': prompt},
])
print(response['message']['content'])

<prompt>What does the Weighted average actuarial assumptions consist of?</prompt>
<context>
Actuarial assumptions The Group’s scheme liabilities are measured using the projected unit credit method using the principal actuarial assumptions set out below:
Notes:
1. Figures shown represent a weighted average assumption of the individual schemes.
2. The rate of increases in pensions in payment and deferred revaluation are dependent on the rate of inflation.

|                | 2019 % | 2018 % | 2017 % |
|----------------|--------|--------|--------|
| Weighted average actuarial assumptions used at 31 March1: |        |        |        |
| Rate of inflation2 |    2.9 |    2.9 |    3.0 |
| Rate of increase in salaries |   2.7 |    2.7 |    2.6 |
| Discount rate |     2.3 |    2.5 |    2.6 |
</context>
<thinking>The user is asking about the components that make up the weighted average actuarial assumptions as listed in the provided financial table. Based on the context, we can infer that the Group's scheme liabilities are measured using specific actuarial assumptions.

The relevant rows from the table indicate the following key factors:
- Rate of inflation (2019: 2.9%, 2018: 2.9%, 2017: 3.0%)
- Rate of increase in salaries (2019: 2.7%, 2018: 2.7%, 2017: 2.6%)
- Discount rate (2019: 2.3%, 2018: 2.5%, 2017: 2.6%)

These factors are essential for calculating the Group's scheme liabilities using the projected unit credit method, as they directly influence how future financial obligations and benefits are valued.

The user intent is to understand which components make up the weighted average actuarial assumptions used in the calculation of the Group’s scheme liabilities.</thinking>
<answer>Final answer: The Weighted average actuarial assumptions consist of three key components:
1. Rate of inflation, which was 2.9% for both 2019 and 2018 and 3.0% for 2017.
2. Rate of increase in salaries, at 2.7% for 2019 and 2018 and 2.6% for 2017.
3. Discount rate, which was 2.3% in 2019, 2.5% in 2018, and 2.6% in 2017.

These factors are integral to the valuation of future liabilities and benefits under the projected unit credit method.</answer>

In [32]:
for i in range(len(df)):
    print(i)
    prompt = sys_prompt + user_prompt.format(df['questions'][i], df['paragraphs'][i]+"\n"+df['table'][i], df['facts'][i], df['answer_type'][i], df['derivation'][i], df['answer'][i], df['scale'][i])
    response = ollama.chat(model='qwen2.5:14b', messages=[
      {'role': 'user', 'content': prompt},
    ])
    print(response['message']['content'])
    with open("/home/rhadamanthys/SyntheticDataGenerator/data/tatqa.txt", "a") as f:
        f.write(f"\n\n\n {response['message']['content']}")
    break

0
<prompt>What does the Weighted average actuarial assumptions consist of?</prompt>
<context>The Group’s scheme liabilities are measured using the projected unit credit method using the principal actuarial assumptions set out below:
Notes: 1 Figures shown represent a weighted average assumption of the individual schemes.
2 The rate of increases in pensions in payment and deferred revaluation are dependent on the rate of inflation.

|             | 2019 % | 2018 % | 2017 % |
|-------------|--------|--------|--------|
| Weighted average actuarial assumptions used at 31 March1:   |        |        |        |
| Rate of inflation2                     | 2.9    | 2.9    | 3.0    |
| Rate of increase in salaries          | 2.7    | 2.7    | 2.6    |
| Discount rate                          | 2.3    | 2.5    | 2.6    |

</context>
<thinking>The user is asking for an explanation of what constitutes the weighted average actuarial assumptions in the context provided. The paragraph notes that figures shown represent a weighted average assumption of the individual schemes, and lists three specific items: Rate of inflation, Rate of increase in salaries, and Discount rate.

The answer type specified is multi-span, which implies there are multiple elements to the answer. Based on this information, we can conclude that the weighted average actuarial assumptions consist of the following components:

- Rate of inflation
- Rate of increase in salaries
- Discount rate

There's no derivation provided or required for this set of assumptions since they're explicitly listed in the table and context.

User intent: To understand what factors are included when calculating weighted average actuarial assumptions.</thinking>
<answer>Final answer: The Weighted average actuarial assumptions consist of the Rate of inflation, Rate of increase in salaries, and Discount rate. These components form part of the principal actuarial assumptions used to measure the Group’s scheme liabilities through the projected unit credit method as specified in the context provided.</answer>

FileNotFoundError: [Errno 2] No such file or directory: './data/tatqa.txt'

In [25]:
len(df)

12830

In [42]:
with open("/home/rhadamanthys/SyntheticDataGenerator/data/tatqa.txt", "a") as f:
    f.write(f"\n\n\n {response['message']['content']}")

In [11]:
with open("/home/rhadamanthys/SyntheticDataGenerator/data/tatqa.txt", "r") as f:
    txt = f.read()

In [12]:
qsn = "What was included therein within the net interest expenses?"

In [13]:
qsn in txt

True

In [10]:
txt

['\n',
 '\n',
 '\n',
 ' <prompt>What does the Weighted average actuarial assumptions consist of?</prompt>\n',
 '<context>\n',
 'Actuarial assumptions The Group’s scheme liabilities are measured using the projected unit credit method using the principal actuarial assumptions set out below:\n',
 'Notes:\n',
 '1 Figures shown represent a weighted average assumption of the individual schemes.\n',
 '2 The rate of increases in pensions in payment and deferred revaluation are dependent on the rate of inflation.\n',
 '\n',
 '|                        | 2019 % | 2018 % | 2017 % |\n',
 '|------------------------|--------|--------|--------|\n',
 '| Weighted average actuarial assumptions used at 31 March1: |          |        |        |\n',
 '| Rate of inflation2     | 2.9    | 2.9    | 3.0    |\n',
 '| Rate of increase in salaries | 2.7   | 2.7    | 2.6    |\n',
 '| Discount rate          | 2.3    | 2.5    | 2.6    |\n',
 '\n',
 "The actual evidence needed: 'Discount rate', 'Rate of increase in salaries', 'Rate of inflation'\n",
 '</context>\n',
 '<thinking>The user is asking for the components that make up the weighted average actuarial assumptions as presented in the table and described by the notes.\n',
 '\n',
 '1. The context provides a list of principal actuarial assumptions used to measure scheme liabilities.\n',
 '2. According to note 1, figures shown represent a weighted average assumption of individual schemes.\n',
 '3. These assumptions include the rate of inflation (as noted in point 2), the rate of increase in salaries, and the discount rate.\n',
 '\n',
 'The evidence listed matches exactly with these components mentioned:\n',
 '- Rate of inflation: 2.9% for both 2018 and 2019; 3.0% in 2017\n',
 '- Rate of increase in salaries: 2.7% in both 2018 and 2019; 2.6% in 2017\n',
 '- Discount rate: 2.3% for 2019, 2.5% for 2018, and 2.6% for 2017\n',
 '\n',
 "This aligns perfectly with the user's request to identify what constitutes the weighted average actuarial assumptions.</thinking>\n",
 '<answer>Final answer: The Weighted Average Actuarial Assumptions consist of three components:\n',
 '- Rate of inflation (measured in percentages, e.g., 2.9% for both 2018 and 2019)\n',
 '- Rate of increase in salaries (measured in percentages, e.g., 2.7% for both 2018 and 2019)\n',
 '- Discount rate (also measured in percentages, varying each year from 2.3% to 2.6%)\n',
 '\n',
 '\n',
 ' <prompt>How much is the 2019 rate of inflation?</prompt>\n',
 '<context>\n',
 'The Group’s scheme liabilities are measured using the projected unit credit method using the principal actuarial assumptions set out below:\n',
 'Notes:\n',
 '1. Figures shown represent a weighted average assumption of the individual schemes.\n',
 '2. The rate of increases in pensions in payment and deferred revaluation are dependent on the rate of inflation.\n',
 '\n',
 '| | 2019 % | 2018 % | 2017 % |\n',
 '|---|--------|--------|--------|\n',
 '| Weighted average actuarial assumptions used at 31 March1: | | | |\n',
 '| Rate of inflation2 | 2.9 | 2.9 | 3.0 |\n',
 '| Rate of increase in salaries | 2.7 | 2.7 | 2.6 |\n',
 '| Discount rate | 2.3 | 2.5 | 2.6 |\n',
 '</context>\n',
 '<thinking>The user is interested in finding the rate of inflation for the year 2019 from the provided financial table. The relevant data point can be found directly in the "Rate of inflation" row under the "2019 %" column.\n',
 '\n',
 "The actual evidence given: ['2.9'] percent.</thinking>\n",
 '<answer>Final answer: The rate of inflation for 2019 is 2.9%. This percentage represents the weighted average rate of increase across various schemes managed by the Group, accounting for factors such as pension payments and deferred revaluation adjustments that are tied to inflation rates.</answer>\n',
 '\n',
 '\n',
 ' <prompt>How much is the 2018 rate of inflation?</prompt>\n',
 '<context>\n',
 'The Group’s scheme liabilities are measured using the projected unit credit method based on principal actuarial assumptions, with figures representing a weighted average assumption of individual schemes. The table below shows the changes in key actuarial assumptions over three years.\n',
 '\n',
 '|                      | 2019 % | 2018 % | 2017 % |\n',
 '|----------------------|--------|--------|--------|\n',
 '| Weighted average actuarial assumptions used at 31 March1: |        |        |        |\n',
 '| Rate of inflation2   | 2.9    | 2.9    | 3.0    |\n',
 '| Rate of increase in salaries | 2.7    | 2.7    | 2.6    |\n',
 '| Discount rate        | 2.3    | 2.5    | 2.6    |\n',
 '</context>\n',
 "<thinking>The user wants to know the exact percentage value for the rate of inflation in 2018 as stated in the context provided. From the table, we see that there is a column for each year and a specific row dedicated to the rate of inflation. The data shows the rate of inflation for 2018 is listed at 2.9%. This value directly corresponds to the user's question.\n",
 '\n',
 'The relevant evidence from the given context is \'2.9\', which aligns with the value provided in the table under the "2018 %" column for the row labeled "Rate of inflation". The scale of this answer is expressed as a percentage, indicating that the rate of inflation is 2.9%.</thinking>\n',
 '<answer>Final answer: The 2018 rate of inflation is 2.9%. This means that according to the given actuarial assumptions table, there was an increase in prices by 2.9% in the year 2018 relative to the previous period as measured under the projected unit credit method.</answer>\n',
 '\n',
 '\n',
 ' <prompt>What is the 2019 average rate of inflation?</prompt>\n',
 '<context>\n',
 'The Group’s scheme liabilities are measured using the projected unit credit method based on principal actuarial assumptions, as outlined below. Note that these figures represent a weighted average assumption of individual schemes and the rate of increases in pensions in payment and deferred revaluation depend on the rate of inflation.\n',
 '\n',
 '|                        | 2019 % | 2018 % | 2017 % |\n',
 '|------------------------|--------|--------|--------|\n',
 '| Weighted average actuarial assumptions used at 31 March1: |        |        |        |\n',
 '| Rate of inflation2     | 2.9    | 2.9    | 3.0    |\n',
 '| Rate of increase in salaries | 2.7   | 2.7   | 2.6   |\n',
 '| Discount rate          | 2.3    | 2.5    | 2.6    |\n',
 '\n',
 '</context>\n',
 '<thinking>The user is asking about the average rate of inflation for 2019, which can be calculated from the provided actuarial assumptions table. Since only one value is given for 2019 (2.9%), we assume this represents both the expected and actual rates of inflation in that year due to no variation specified between them.\n',
 '\n',
 'Calculation:\n',
 '- Average rate of inflation = (Rate of inflation in 2019 + Rate of inflation in 2018) / 2\n',
 '- Given: Rate of inflation for 2019 is 2.9%, and rate of inflation for 2018 is also 2.9%\n',
 '\n',
 'Therefore, the average rate of inflation calculation would be:\n',
 '(2.9 + 2.9) / 2 = 2.9\n',
 '\n',
 'This calculation assumes that the context indicates a consistent rate between years unless specified otherwise.</thinking>\n',
 '<answer>Final answer: The average rate of inflation for 2019 is 2.9 percent, calculated by averaging the 2019 and 2018 rates since both are provided as 2.9%. This value represents an unchanging trend in inflation over these two consecutive years according to the actuarial assumptions table.</answer>\n',
 '\n',
 '\n',
 ' <prompt>What is the 2019 average rate of increase in salaries?</prompt>\n',
 '<context>\n',
 'The Group’s scheme liabilities are measured using the projected unit credit method with the principal actuarial assumptions as follows:\n',
 '\n',
 'Notes:\n',
 '1. Figures shown represent a weighted average assumption of the individual schemes.\n',
 '2. The rate of increases in pensions in payment and deferred revaluation are dependent on the rate of inflation.\n',
 '\n',
 '|                | 2019 % | 2018 % | 2017 % |\n',
 '|----------------|--------|--------|--------|\n',
 '| Weighted average actuarial assumptions used at 31 March1: |      |      |      |\n',
 '| Rate of inflation2             | 2.9   | 2.9   | 3.0   |\n',
 '| Rate of increase in salaries   | 2.7   | 2.7   | 2.6   |\n',
 '| Discount rate                  | 2.3   | 2.5   | 2.6   |\n',
 '</context>\n',
 "<thinking>The user is asking for the average rate of salary increase specifically in the year 2019, which can be found in the financial table under the 'Rate of increase in salaries' column and row corresponding to the year 2019. The context provided does not contain a separate section indicating yearly variations within 2019; therefore, the rate for 2019 is simply stated as 2.7% according to the given table.\n",
 '\n',
 'However, since the user\'s prompt asks specifically about an "average," it might be inferred that they seek a comparison or average between years prior to 2019 and possibly including 2018, which also has an identical rate of increase in salaries at 2.7%.\n',
 '\n',
 'The calculation for the average is (2.7 + 2.7) / 2 = 2.7.\n',
 '\n',
 "Thus, interpreting the user's intent could be that they are asking about an average considering the rates from both 2019 and 2018.</thinking>\n",
 '<answer>Final answer: The average rate of increase in salaries for 2019, when compared with the same rate from 2018 (as there is no variation within years according to the provided context), is 2.7%. This value represents a consistent trend over two consecutive years.</answer>\n',
 '\n',
 '\n',
 ' <prompt>How was internally developed software capitalised?</prompt>\n',
 '<context>\n',
 'Internally generated software is capitalised at cost less accumulated amortisation. Amortisation is calculated using the straight-line basis over the asset’s useful economic life, which is generally two to three years. Their useful lives and potential impairment are reviewed at the end of each financial year.\n',
 '</context>\n',
 '<thinking>\n',
 'The user wants to know how internally developed software is capitalised according to the provided context.\n',
 '\n',
 'From the paragraph:\n',
 '- Internally generated software is capitalised at cost less accumulated amortisation.\n',
 '- Amortisation is calculated using the straight-line basis over the asset’s useful economic life, which ranges from two to three years.\n',
 '- Their useful lives and potential impairment are reviewed annually.\n',
 '\n',
 'Based on this information, we can conclude that internally developed software is recorded in the balance sheet at its initial cost minus any accumulated amortization. The amortisation of these assets is done using a straight-line method over their estimated useful life, typically between two to three years.\n',
 '</thinking>\n',
 '<answer>\n',
 "Final answer: Internally developed software is capitalised at cost less accumulated amortisation and amortized on a straight-line basis over its economic useful life, which generally ranges from two to three years. The review of the asset's useful life and potential impairment takes place annually.\n",
 '</answer>\n',
 '\n',
 '\n',
 ' <prompt>How much was the closing net book amount for software under development in 2019?</prompt>\n',
 '<context>\n',
 '11 Intangible assets (continued) (a) Intangible assets RIGHTS AND LICENCES Certain licences that NEXTDC possesses have an indefinite useful life and are carried at cost less impairment losses and are subject to impairment review at least annually and whenever there is an indication that it may be impaired. Other licences that NEXTDC acquires are carried at cost less accumulated amortisation and accumulated impairment losses. Amortisation is recognised on a straight-line basis over the estimated useful life.\n',
 'INTERNALLY GENERATED SOFTWARE Internally developed software is capitalised at cost less accumulated amortisation. Amortisation is calculated using the straight-line basis over the asset’s useful economic life which is generally two to three years. Their useful lives and potential impairment are reviewed at the end of each financial year.\n',
 'SOFTWARE UNDER DEVELOPMENT Costs incurred in developing products or systems and costs incurred in acquiring software and licenses that will contribute to future period financial benefits through revenue generation and/or cost reduction are capitalised to software and systems. Costs capitalised include external direct costs of materials and services and employee costs. Assets in the course of construction include only those costs directly attributable to the development phase and are only recognised following completion of technical feasibility and where the Group has an intention and ability to use the asset.\n',
 '\n',
 '<table>\n',
 '<thead>\n',
 '<tr><th></th><th>Rights and licenses</th><th>Internally generated software</th><th>Software under development</th><th>Total</th></tr>\n',
 '</thead>\n',
 '<tbody>\n',
 "<tr><td>Movements $'000</td><td></td><td></td><td></td><td></td></tr>\n",
 '<tr><td>At 30 June 2019</td><td></td><td></td><td></td><td></td></tr>\n',
 '<tr><td>Cost</td><td>13</td><td>12,961</td><td>16,284</td><td>29,259</td></tr>\n',
 '<tr><td>Accumulated amortisation</td><td>-</td><td>(5,580)</td><td>-</td><td>(5,580)</td></tr>\n',
 '<tr><td>Netbook amount</td><td>13</td><td>7,381</td><td>16,284</td><td>23,678</td></tr>\n',
 '<tr><td>30 June 2018</td><td></td><td></td><td></td><td></td></tr>\n',
 '<tr><td>Opening net book amount at 1 July 2017</td><td>43</td><td>442</td><td>8,053</td><td>8,538</td></tr>\n',
 '<tr><td>Additions – externally acquired</td><td>13</td><td>-</td><td>5,253</td><td>5,266</td></tr>\n',
 '<tr><td>Additions – internally developed</td><td>-</td><td>-</td><td>1,256</td><td>1,256</td></tr>\n',
 '<tr><td>Amortisation</td><td>(43)</td><td>(1,746)</td><td>-</td><td>(1,789)</td></tr>\n',
 '<tr><td>Transfers</td><td>-</td><td>7,563</td><td>(7,563)</td><td>-</td></tr>\n',
 '<tr><td>Transfer between classes</td><td>-</td><td>744</td><td>-</td><td>744</td></tr>\n',
 '<tr><td>Disposals</td><td>-</td><td>(618)</td><td>(490)</td><td>(1,108)</td></tr>\n',
 '<tr><td>Closing net book amount</td><td>13</td><td>6,385</td><td>6,509</td><td>12,907</td></tr>\n',
 '<tr><td>At 30 June 2018</td><td></td><td></td><td></td><td></td></tr>\n',
 '<tr><td>Cost</td><td>104</td><td>9,555</td><td>6,509</td><td>16,168</td></tr>\n',
 '<tr><td>Accumulated amortisation</td><td>(91)</td><td>(3,170)</td><td>-</td><td>(3,261)</td></tr>\n',
 '<tr><td>Net book amount</td><td>13</td><td>6,385</td><td>6,509</td><td>12,907</td></tr>\n',
 '</tbody>\n',
 '</table>\n',
 '</context>\n',
 '<thinking>The user wants to know the closing net book amount for software under development in 2019. From the financial table provided, we can see that there are two key figures related to software under development: the cost at 30 June 2019 and the closing net book amount for the same period.\n',
 '\n',
 '- Cost of Software Under Development at 30 June 2019: $16,284 thousand\n',
 '- Netbook Amount (Closing) of Software Under Development in 2019: The table shows that the accumulated amortisation is zero and the cost equals the net book amount as no specific amortization or impairment adjustments are mentioned for software under development.\n',
 '\n',
 "Hence, the closing net book amount for software under development is directly derived from its cost since there's no detailed amortisation schedule provided specifically for this asset class. Therefore, we can use the $16,284 thousand figure.</thinking>\n",
 '<answer>Final answer: The closing net book amount for software under development in 2019 was $16,284 (in thousands).</answer>\n',
 '\n',
 '\n',
 ' <prompt>What was the total cost for 2019?</prompt>\n',
 '<context>\n',
 'The provided context includes details about intangible assets such as rights and licences, internally generated software, and software under development. A financial table outlines movements in these assets from June 30, 2018 to June 30, 2019.\n',
 '\n',
 'Financial Table:\n',
 '| Movements | Rights and licenses | Internally generated software | Software under development | Total |\n',
 '| --------- | -------------------- | ----------------------------- | -------------------------- | ----- |\n',
 '| At 30 Jun 2019 | - | - | - | - |\n',
 '| Cost      | 13                  | 12,961                       | 16,284                    | 29,259|\n',
 '| Accumulated amortisation | -          | (5,580)                      | -                         | (5,580)|\n',
 '| Netbook amount | 13                | 7,381                        | 16,284                    | 23,678|\n',
 '\n',
 'The table shows the total cost for each category of intangible assets and provides a summary at the bottom.\n',
 '</context>\n',
 '<thinking>The user wants to know the total cost incurred in the year 2019. The relevant information is found under "Movements" for the period ending June 30, 2019. The "Cost" row indicates the costs associated with each category of intangible assets.\n',
 '\n',
 '- Rights and licences: $13,000 (the value after removing thousands)\n',
 '- Internally generated software: $12,961,000\n',
 '- Software under development: $16,284,000\n',
 '\n',
 'To find the total cost for 2019, we need to sum up these individual costs:\n',
 '\\[ \\text{Total Cost} = \\$13,000 + \\$12,961,000 + \\$16,284,000 \\]\n',
 '\n',
 'The summary row "Total" already provides the total cost in thousand dollars.\n',
 '</thinking>\n',
 '<answer>Final answer: The total cost for 2019 was $29,259,000 (or 29,259 in thousands).</answer>\n',
 '\n',
 '\n',
 ' <prompt>\n',
 'What was the percentage change in cost of software under development between 2018 and 2019?\n',
 '</prompt>\n',
 '<context>\n',
 'The relevant data from the table for the context provided includes:\n',
 "- At 30 June 2019, Software under development: $'000 (Cost) = 16,284\n",
 "- At 30 June 2018, Closing net book amount (Software under development): $'000 = 6,509\n",
 '\n',
 'The cost of software under development increased from $6,509,000 in 2018 to $16,284,000 in 2019.\n',
 '</context>\n',
 '<thinking>\n',
 'To calculate the percentage change in the cost of software under development between 2018 and 2019, we follow these steps:\n',
 '\n',
 'Step 1: Identify the initial value (in 2018) and the final value (in 2019).\n',
 '- Initial Cost of Software Under Development = $6,509,000\n',
 '- Final Cost of Software Under Development = $16,284,000\n',
 '\n',
 'Step 2: Calculate the absolute change.\n',
 'Absolute Change = Final Value - Initial Value \n',
 '= $16,284,000 - $6,509,000 = $9,775,000 \n',
 '\n',
 'Step 3: Use the formula for percentage change:\n',
 'Percentage Change = (Absolute Change / Initial Value) * 100\n',
 '= ($9,775,000 / $6,509,000) * 100\n',
 '\n',
 'Step 4: Perform the calculation.\n',
 'Percentage Change = (9,775,000 / 6,509,000) * 100\n',
 '= 1.5018273... * 100\n',
 '= 150.18%\n',
 '\n',
 'The percentage change in the cost of software under development between 2018 and 2019 is therefore 150.18%.\n',
 '</thinking>\n',
 '<answer>\n',
 'Final answer: The percentage increase in the cost of software under development from 2018 to 2019 was 150.18%. This significant growth indicates a substantial investment by NEXTDC in developing new software or systems over this period, which could be attributed to expansion plans, technological upgrades, or improvements aimed at generating revenue and reducing costs.\n',
 '</answer>\n',
 '\n',
 '\n',
 ' <prompt>Which year has greater total accumulated amortisation?</prompt>\n',
 '<context>\n',